/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LogseqBlockRefEnhancer
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/services/BlockParser.ts
var BlockParser = class {
  constructor() {
    this.PAGE_PROPS_REGEX = /^\s*[^-\s].*?::\s*.*$/;
    this.BLOCK_CONTENT_REGEX = /^(\s*)-\s(.+)/;
    this.BLOCK_ID_REGEX = /^\s*id::\s*([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})/;
    this.BLOCK_PROPS_REGEX = /^\s*([^-\s].*?::\s*.*)$/;
  }
  appendChildLine(target, line) {
    target.childrenMarkdown = target.childrenMarkdown ? `${target.childrenMarkdown}
${line}` : line;
  }
  parse(filePath, content) {
    const lines = content.split("\n");
    const allFoundBlocks = [];
    const parentStack = [];
    let inPageProperties = true;
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      if (inPageProperties) {
        if (this.PAGE_PROPS_REGEX.test(line) || line.trim() === "") {
          continue;
        }
        inPageProperties = false;
      }
      const blockMatch = line.match(this.BLOCK_CONTENT_REGEX);
      if (blockMatch) {
        const indentation = blockMatch[1].length;
        const rawContent = blockMatch[2];
        const newBlock = {
          block: {
            filePath,
            rawContent,
            childrenMarkdown: "",
            startLine: i,
            childrenIDs: []
          },
          indentation,
          line: i
        };
        while (parentStack.length > 0 && parentStack[parentStack.length - 1].indentation >= indentation) {
          parentStack.pop();
        }
        for (const ancestor of parentStack) {
          this.appendChildLine(ancestor.block, line);
        }
        if (parentStack.length > 0) {
          const parent = parentStack[parentStack.length - 1];
          parent.block._children = parent.block._children || [];
          parent.block._children.push(newBlock);
        }
        parentStack.push(newBlock);
        allFoundBlocks.push(newBlock);
      } else {
        const lastBlock = allFoundBlocks[allFoundBlocks.length - 1];
        if (!lastBlock)
          continue;
        const idMatch = line.match(this.BLOCK_ID_REGEX);
        if (idMatch && i === lastBlock.line + 1) {
          const idIndentation = line.indexOf("id::");
          if (idIndentation > lastBlock.indentation) {
            lastBlock.id = idMatch[1];
            continue;
          }
        }
        const propMatch = line.match(this.BLOCK_PROPS_REGEX);
        if (propMatch) {
          const propIndentation = line.indexOf(propMatch[1]);
          if (propIndentation > lastBlock.indentation) {
            lastBlock.block.rawContent += "\n" + line;
            for (let index = 0; index < parentStack.length - 1; index++) {
              this.appendChildLine(parentStack[index].block, line);
            }
          }
        }
      }
    }
    const finalIndex = /* @__PURE__ */ new Map();
    for (const blockInProgress of allFoundBlocks) {
      if (blockInProgress.block._children) {
        blockInProgress.block.childrenIDs = blockInProgress.block._children.map((child) => child.id).filter((id) => !!id);
        delete blockInProgress.block._children;
      }
      if (blockInProgress.id) {
        finalIndex.set(blockInProgress.id, blockInProgress.block);
      }
    }
    return finalIndex;
  }
};

// src/services/IndexService.ts
var import_obsidian = require("obsidian");
var IndexService = class {
  constructor(app, pluginDataPath) {
    this.app = app;
    this.blockParser = new BlockParser();
    this.index = /* @__PURE__ */ new Map();
    this.CACHE_FILE_PATH = `${pluginDataPath}/block-cache.json`;
    this.debouncedSave = (0, import_obsidian.debounce)(() => this.saveIndexToCache(), 1e3, true);
  }
  /**
   * Builds the index for the entire vault.
   */
  async initialize() {
    const loaded = await this.loadIndexFromCache();
    if (!loaded) {
      await this.buildIndex();
    }
  }
  async saveIndexToCache() {
    try {
      const data = JSON.stringify(Array.from(this.index.entries()));
      await this.app.vault.adapter.write(this.CACHE_FILE_PATH, data);
    } catch (error) {
      console.error("Error saving index to cache:", error);
    }
    console.log(`%c[IndexService] INITIALIZED. Index size: ${this.index.size}`, "background: #222; color: #bada55");
  }
  async loadIndexFromCache() {
    try {
      if (!await this.app.vault.adapter.exists(this.CACHE_FILE_PATH)) {
        return false;
      }
      const data = await this.app.vault.adapter.read(this.CACHE_FILE_PATH);
      const entries = JSON.parse(data);
      if (entries.some(([, block]) => typeof block.childrenMarkdown !== "string")) {
        return false;
      }
      this.index = new Map(entries);
      return true;
    } catch (error) {
      console.error("Error loading index from cache:", error);
      return false;
    }
  }
  async buildIndex() {
    this.index.clear();
    const markdownFiles = this.app.vault.getMarkdownFiles();
    let processedCount = 0;
    for (const file of markdownFiles) {
      const content = await this.app.vault.cachedRead(file);
      const fileBlocks = this.blockParser.parse(file.path, content);
      fileBlocks.forEach((block, id) => {
        this.index.set(id, block);
      });
      processedCount++;
      if (processedCount % 100 === 0) {
        await new Promise((resolve) => setTimeout(resolve, 0));
      }
    }
    await this.saveIndexToCache();
  }
  async processFileChange(file) {
    this.removeFileFromIndex(file.path);
    const content = await this.app.vault.cachedRead(file);
    const fileBlocks = this.blockParser.parse(file.path, content);
    fileBlocks.forEach((block, id) => {
      this.index.set(id, block);
    });
    this.debouncedSave();
  }
  processFileDelete(filePath) {
    this.removeFileFromIndex(filePath);
    this.debouncedSave();
  }
  processFileRename(oldPath, newPath) {
    for (const block of this.index.values()) {
      if (block.filePath === oldPath) {
        block.filePath = newPath;
      }
    }
    this.debouncedSave();
  }
  getBlock(id) {
    console.log(`[IndexService] GET_BLOCK called for ID: ${id}. Current index size: ${this.index.size}`);
    return this.index.get(id);
  }
  searchBlocks(query) {
    if (!query)
      return [];
    const lowerCaseQuery = query.toLowerCase();
    const results = [];
    for (const [id, block] of this.index.entries()) {
      if (block.rawContent.toLowerCase().includes(lowerCaseQuery)) {
        results.push({ id, block });
      }
    }
    return results.slice(0, 50);
  }
  findBlockByFileAndLine(filePath, line) {
    for (const [id, block] of this.index.entries()) {
      if (block.filePath === filePath && block.startLine === line) {
        return { id, block };
      }
    }
    return null;
  }
  addBlock(id, block) {
    this.index.set(id, block);
    this.debouncedSave();
  }
  removeFileFromIndex(filePath) {
    const idsToRemove = [];
    for (const [id, block] of this.index.entries()) {
      if (block.filePath === filePath) {
        idsToRemove.push(id);
      }
    }
    idsToRemove.forEach((id) => this.index.delete(id));
  }
};

// src/editor/BlockSuggest.ts
var import_obsidian2 = require("obsidian");
var BlockSuggest = class extends import_obsidian2.EditorSuggest {
  constructor(app, indexService) {
    super(app);
    this.indexService = indexService;
  }
  onTrigger(cursor, editor, file) {
    const line = editor.getLine(cursor.line);
    const subline = line.substring(0, cursor.ch);
    const match = subline.match(/\(\(([^)]*)$/);
    if (match) {
      return {
        start: { line: cursor.line, ch: match.index },
        end: cursor,
        query: match[1]
      };
    }
    return null;
  }
  getSuggestions(context) {
    return this.indexService.searchBlocks(context.query);
  }
  renderSuggestion(item, el) {
    el.createEl("div", { text: item.block.rawContent.substring(0, 100) });
    el.createEl("small", { text: item.block.filePath, cls: "logseq-suggest-filepath" });
  }
  selectSuggestion(item, evt) {
    if (!this.context)
      return;
    const replacement = `((${item.id}))`;
    this.context.editor.replaceRange(replacement, this.context.start, this.context.end);
  }
};

// src/editor/BlockReferenceField.ts
var import_state = require("@codemirror/state");
var import_view2 = require("@codemirror/view");

// src/editor/BlockReferenceWidget.ts
var import_view = require("@codemirror/view");
var BlockReferenceWidget = class extends import_view.WidgetType {
  constructor(state, mode, content, interaction) {
    super();
    this.state = state;
    this.mode = mode;
    this.content = content;
    this.interaction = interaction;
  }
  eq(other) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p, _q, _r, _s, _t, _u, _v, _w, _x, _y, _z, _A, _B;
    return this.state === other.state && this.mode === other.mode && this.content === other.content && ((_a = this.interaction) == null ? void 0 : _a.from) === ((_b = other.interaction) == null ? void 0 : _b.from) && ((_c = this.interaction) == null ? void 0 : _c.to) === ((_d = other.interaction) == null ? void 0 : _d.to) && ((_e = this.interaction) == null ? void 0 : _e.revealPos) === ((_f = other.interaction) == null ? void 0 : _f.revealPos) && ((_g = this.interaction) == null ? void 0 : _g.blockWidget) === ((_h = other.interaction) == null ? void 0 : _h.blockWidget) && ((_i = this.interaction) == null ? void 0 : _i.preserveListMarker) === ((_j = other.interaction) == null ? void 0 : _j.preserveListMarker) && ((_k = this.interaction) == null ? void 0 : _k.availableInlineWidthPx) === ((_l = other.interaction) == null ? void 0 : _l.availableInlineWidthPx) && ((_m = this.interaction) == null ? void 0 : _m.listPrefixColumns) === ((_n = other.interaction) == null ? void 0 : _n.listPrefixColumns) && ((_o = this.interaction) == null ? void 0 : _o.listMarkerOffsetPx) === ((_p = other.interaction) == null ? void 0 : _p.listMarkerOffsetPx) && ((_q = this.interaction) == null ? void 0 : _q.listContentOffsetPx) === ((_r = other.interaction) == null ? void 0 : _r.listContentOffsetPx) && ((_s = this.interaction) == null ? void 0 : _s.cardPos) === ((_t = other.interaction) == null ? void 0 : _t.cardPos) && ((_u = this.interaction) == null ? void 0 : _u.refId) === ((_v = other.interaction) == null ? void 0 : _v.refId) && ((_w = this.interaction) == null ? void 0 : _w.signature) === ((_x = other.interaction) == null ? void 0 : _x.signature) && ((_y = this.interaction) == null ? void 0 : _y.lineHeightPx) === ((_z = other.interaction) == null ? void 0 : _z.lineHeightPx) && ((_A = this.interaction) == null ? void 0 : _A.reservedHeightPx) === ((_B = other.interaction) == null ? void 0 : _B.reservedHeightPx);
  }
  ignoreEvent(event) {
    if (this.mode !== "embed") {
      return true;
    }
    return event.type !== "mousedown";
  }
  createEmbedCard(isBlockWidget, isListCard) {
    var _a, _b, _c;
    const card = document.createElement("div");
    const usesMeasuredListLayout = ((_a = this.interaction) == null ? void 0 : _a.listMarkerOffsetPx) !== void 0 && ((_b = this.interaction) == null ? void 0 : _b.listContentOffsetPx) !== void 0;
    const preservesListMarker = ((_c = this.interaction) == null ? void 0 : _c.preserveListMarker) === true;
    card.className = `logseq-block-ref-enhancer-widget logseq-block-embed-widget markdown-rendered${isBlockWidget ? "" : " is-inline-embed"}${isListCard ? " is-list-embed-card" : ""}${usesMeasuredListLayout ? " is-measured-list-embed" : ""}${preservesListMarker ? " is-list-inline-embed" : ""}`;
    if (this.interaction) {
      card.dataset.logseqFrom = String(this.interaction.from);
      card.dataset.logseqTo = String(this.interaction.to);
      card.dataset.logseqRevealPos = String(this.interaction.revealPos);
      if (this.interaction.refId) {
        card.dataset.logseqRefId = this.interaction.refId;
      }
      if (this.interaction.availableInlineWidthPx !== void 0) {
        card.style.setProperty("--logseq-inline-available-width-px", `${this.interaction.availableInlineWidthPx}px`);
      }
      if (this.interaction.listPrefixColumns !== void 0) {
        card.style.setProperty("--logseq-list-prefix-columns", `${this.interaction.listPrefixColumns}ch`);
      }
      if (this.interaction.listMarkerOffsetPx !== void 0) {
        card.style.setProperty("--logseq-list-marker-offset-px", `${this.interaction.listMarkerOffsetPx}px`);
      }
      if (this.interaction.listContentOffsetPx !== void 0) {
        card.style.setProperty("--logseq-list-content-offset-px", `${this.interaction.listContentOffsetPx}px`);
      }
      if (this.interaction.lineHeightPx !== void 0) {
        card.style.setProperty("--logseq-line-height-px", `${this.interaction.lineHeightPx}px`);
      }
    }
    if (this.mode === "embed" && usesMeasuredListLayout && !preservesListMarker) {
      const layout = document.createElement("div");
      layout.className = "logseq-live-preview-list-embed";
      const marker = document.createElement("span");
      marker.className = "logseq-live-preview-list-marker";
      marker.setAttribute("aria-hidden", "true");
      const embed = document.createElement("div");
      embed.className = "logseq-block-embed logseq-live-preview-embed-card";
      if (this.state === "loading") {
        embed.setText("Loading block...");
        card.addClass("is-loading");
      } else if (this.state === "rendered" && this.content) {
        embed.innerHTML = this.content;
      } else {
        embed.setText("Error: Invalid state");
        card.addClass("is-error");
      }
      layout.append(marker, embed);
      card.appendChild(layout);
      return card;
    }
    if (this.state === "loading") {
      card.setText(this.mode === "embed" ? "Loading block..." : "Loading...");
      card.addClass("is-loading");
    } else if (this.state === "rendered" && this.content) {
      if (this.mode === "embed") {
        card.innerHTML = this.content;
      } else {
        card.setText(this.content);
      }
    } else {
      card.setText("Error: Invalid state");
      card.addClass("is-error");
    }
    return card;
  }
  createListEmbedSpacer() {
    var _a, _b;
    const spacer = document.createElement("div");
    spacer.className = "logseq-block-embed-spacer";
    const reservedHeight = Math.max((_b = (_a = this.interaction) == null ? void 0 : _a.reservedHeightPx) != null ? _b : 0, 0);
    spacer.style.height = `${reservedHeight}px`;
    return spacer;
  }
  toDOM() {
    var _a, _b, _c;
    const isBlockWidget = (_b = (_a = this.interaction) == null ? void 0 : _a.blockWidget) != null ? _b : this.mode === "embed";
    const isListCard = ((_c = this.interaction) == null ? void 0 : _c.cardPos) !== void 0;
    if (this.mode === "embed" && isListCard) {
      return this.createListEmbedSpacer();
    }
    const container = document.createElement(this.mode === "embed" ? "div" : "span");
    if (this.mode === "embed") {
      return this.createEmbedCard(isBlockWidget, false);
    } else {
      container.className = "logseq-block-ref-enhancer-widget logseq-inline-block-ref";
    }
    if (this.state === "loading") {
      container.setText("Loading...");
      container.addClass("is-loading");
    } else if (this.state === "rendered" && this.content) {
      container.setText(this.content);
    } else {
      container.setText("Error: Invalid state");
      container.addClass("is-error");
    }
    return container;
  }
};

// src/editor/BlockReferenceField.ts
var addLoadingWidgetEffect = import_state.StateEffect.define();
var setRenderedWidgetEffect = import_state.StateEffect.define();
var removeWidgetEffect = import_state.StateEffect.define();
var blockReferenceField = import_state.StateField.define({
  // 创建一个空的装饰集
  create() {
    return import_view2.Decoration.none;
  },
  // `update` 函数现在是状态机：它只响应传入的消息 (effects)
  update(widgets, tr) {
    var _a, _b, _c, _d;
    widgets = widgets.map(tr.changes);
    for (const effect of tr.effects) {
      if (effect.is(addLoadingWidgetEffect)) {
        const { from, to, mode, interaction } = effect.value;
        const refId = (_a = interaction == null ? void 0 : interaction.refId) != null ? _a : `${mode}:${from}:${to}`;
        const signature = interaction == null ? void 0 : interaction.signature;
        if (mode === "embed" && (interaction == null ? void 0 : interaction.cardPos) !== void 0) {
          const source = import_view2.Decoration.replace({
            logseqRefId: refId,
            logseqRole: "source",
            logseqSignature: signature
          }).range(from, to);
          const card = import_view2.Decoration.widget({
            widget: new BlockReferenceWidget("loading", mode, void 0, {
              ...interaction,
              blockWidget: true,
              refId
            }),
            block: true,
            side: 1,
            logseqRefId: refId,
            logseqRole: "card",
            logseqSignature: signature
          }).range(interaction.cardPos);
          widgets = widgets.update({
            filter: (aFrom, aTo, value) => value.spec.logseqRefId !== refId && (aTo <= from || aFrom >= to),
            add: [source, card],
            sort: true
          });
          continue;
        }
        const isBlockWidget = (_b = interaction == null ? void 0 : interaction.blockWidget) != null ? _b : mode === "embed";
        const loading = import_view2.Decoration.replace({
          widget: new BlockReferenceWidget("loading", mode, void 0, interaction ? { ...interaction, refId } : void 0),
          block: isBlockWidget,
          logseqRefId: refId,
          logseqRole: "single",
          logseqSignature: signature
        }).range(from, to);
        widgets = widgets.update({
          // 移除与此范围重叠的旧装饰，避免重复
          filter: (aFrom, aTo, value) => value.spec.logseqRefId !== refId && (aTo <= from || aFrom >= to),
          add: [loading]
        });
      } else if (effect.is(setRenderedWidgetEffect)) {
        const { from, to, content, mode, interaction } = effect.value;
        const refId = (_c = interaction == null ? void 0 : interaction.refId) != null ? _c : `${mode}:${from}:${to}`;
        const signature = interaction == null ? void 0 : interaction.signature;
        if (mode === "embed" && (interaction == null ? void 0 : interaction.cardPos) !== void 0) {
          const source = import_view2.Decoration.replace({
            logseqRefId: refId,
            logseqRole: "source",
            logseqSignature: signature
          }).range(from, to);
          const card = import_view2.Decoration.widget({
            widget: new BlockReferenceWidget("rendered", mode, content, {
              ...interaction,
              blockWidget: true,
              refId
            }),
            block: true,
            side: 1,
            logseqRefId: refId,
            logseqRole: "card",
            logseqSignature: signature
          }).range(interaction.cardPos);
          widgets = widgets.update({
            filter: (aFrom, aTo, value) => value.spec.logseqRefId !== refId && (aTo <= from || aFrom >= to),
            add: [source, card],
            sort: true
          });
          continue;
        }
        const isBlockWidget = (_d = interaction == null ? void 0 : interaction.blockWidget) != null ? _d : mode === "embed";
        const rendered = import_view2.Decoration.replace({
          widget: new BlockReferenceWidget("rendered", mode, content, interaction ? { ...interaction, refId } : void 0),
          block: isBlockWidget,
          logseqRefId: refId,
          logseqRole: "single",
          logseqSignature: signature
        }).range(from, to);
        widgets = widgets.update({
          filter: (aFrom, aTo, value) => value.spec.logseqRefId !== refId && (aTo <= from || aFrom >= to),
          add: [rendered]
        });
      } else if (effect.is(removeWidgetEffect)) {
        const { from, to, refId } = effect.value;
        widgets = widgets.update({
          filter: (aFrom, aTo, value) => {
            if (refId && value.spec.logseqRefId === refId) {
              return false;
            }
            return aTo <= from || aFrom >= to;
          }
        });
      }
    }
    return widgets;
  },
  // 告诉编辑器，这个 StateField 提供了需要被渲染到视图中的装饰
  provide: (f) => import_view2.EditorView.decorations.from(f)
});

// src/editor/AsyncBlockRendererPlugin.ts
var import_obsidian3 = require("obsidian");
var import_state2 = require("@codemirror/state");
var import_view3 = require("@codemirror/view");
var EMBED_BLOCK_REF_REGEX = /\{\{embed\s+\(\(([A-Za-z0-9_-]{36,})\)\)\s*\}\}/y;
var INLINE_BLOCK_REF_REGEX = /\(\(([A-Za-z0-9_-]{36,})\)\)/y;
var FULLWIDTH_INLINE_BLOCK_REF_REGEX = /（（([A-Za-z0-9_-]{36,})））/y;
var FENCE_REGEX = /^\s{0,3}(`{3,}|~{3,})/;
function buildTargetSignature(target) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k;
  return `${target.from}:${target.to}:${target.mode}:${target.uuid}:${target.blockWidget ? 1 : 0}:${target.preserveListMarker ? 1 : 0}:${(_a = target.availableInlineWidthPx) != null ? _a : -1}:${target.renderAsListItem ? 1 : 0}:${(_b = target.indentColumns) != null ? _b : 0}:${(_c = target.listMarkerOffsetPx) != null ? _c : -1}:${(_d = target.listContentOffsetPx) != null ? _d : -1}:${(_e = target.revealPos) != null ? _e : -1}:${(_f = target.revealFrom) != null ? _f : -1}:${(_g = target.revealTo) != null ? _g : -1}:${(_h = target.cardPos) != null ? _h : -1}:${(_i = target.refId) != null ? _i : ""}:${(_j = target.lineHeightPx) != null ? _j : -1}:${(_k = target.reservedHeightPx) != null ? _k : -1}`;
}
function buildRenderSignature(target) {
  var _a, _b, _c, _d, _e;
  return `${target.from}:${target.to}:${target.mode}:${target.uuid}:${target.preserveListMarker ? 1 : 0}:${(_a = target.availableInlineWidthPx) != null ? _a : -1}:${target.renderAsListItem ? 1 : 0}:${(_b = target.refId) != null ? _b : ""}:${(_c = target.listMarkerOffsetPx) != null ? _c : -1}:${(_d = target.listContentOffsetPx) != null ? _d : -1}:${(_e = target.lineHeightPx) != null ? _e : -1}`;
}
function getTargetRefId(target) {
  var _a;
  return (_a = target.refId) != null ? _a : `${target.mode}:${target.from}:${target.to}`;
}
function getFenceState(line) {
  const match = line.match(FENCE_REGEX);
  if (!match) {
    return null;
  }
  const marker = match[1];
  return {
    char: marker[0],
    length: marker.length
  };
}
function isClosingFence(line, fenceState) {
  const closingRegex = new RegExp(`^\\s{0,3}${fenceState.char}{${fenceState.length},}\\s*$`);
  return closingRegex.test(line);
}
function findInlineCodeSpanEnd(line, start) {
  let ticks = 0;
  while (start + ticks < line.length && line[start + ticks] === "`") {
    ticks++;
  }
  const delimiter = "`".repeat(ticks);
  const closingIndex = line.indexOf(delimiter, start + ticks);
  if (closingIndex === -1) {
    return start + ticks;
  }
  return closingIndex + ticks;
}
function scanLineForTargets(line, lineOffset, targets) {
  const standaloneEmbedListMatch = line.match(/^(\s*)-\s+(\{\{embed\s+\(\(([A-Za-z0-9_-]{36,})\)\)\s*\}\})\s*$/);
  if (standaloneEmbedListMatch) {
    const embedStart = line.indexOf("{{embed");
    const embedSyntax = standaloneEmbedListMatch[2];
    targets.push({
      from: lineOffset + embedStart,
      to: lineOffset + embedStart + embedSyntax.length,
      uuid: standaloneEmbedListMatch[3],
      mode: "embed",
      blockWidget: false,
      preserveListMarker: true,
      revealPos: lineOffset + embedStart,
      revealFrom: lineOffset + embedStart,
      revealTo: lineOffset + embedStart + embedSyntax.length,
      refId: `embed-list:${lineOffset}:${lineOffset + line.length}`
    });
    return;
  }
  const standaloneEmbedMatch = line.match(/^\s*\{\{embed\s+\(\(([A-Za-z0-9_-]{36,})\)\)\s*\}\}\s*$/);
  if (standaloneEmbedMatch) {
    targets.push({
      from: lineOffset,
      to: lineOffset + line.length,
      uuid: standaloneEmbedMatch[1],
      mode: "embed",
      blockWidget: true,
      revealPos: lineOffset + line.indexOf("{{embed"),
      revealFrom: lineOffset,
      revealTo: lineOffset + line.length,
      refId: `embed-block:${lineOffset}:${lineOffset + line.length}`
    });
    return;
  }
  let index = 0;
  while (index < line.length) {
    if (line[index] === "`") {
      index = findInlineCodeSpanEnd(line, index);
      continue;
    }
    EMBED_BLOCK_REF_REGEX.lastIndex = index;
    const embedMatch = EMBED_BLOCK_REF_REGEX.exec(line);
    if (embedMatch) {
      index = embedMatch.index + embedMatch[0].length;
      continue;
    }
    INLINE_BLOCK_REF_REGEX.lastIndex = index;
    const inlineMatch = INLINE_BLOCK_REF_REGEX.exec(line);
    if (inlineMatch) {
      targets.push({
        from: lineOffset + inlineMatch.index,
        to: lineOffset + inlineMatch.index + inlineMatch[0].length,
        uuid: inlineMatch[1],
        mode: "inline"
      });
      index = inlineMatch.index + inlineMatch[0].length;
      continue;
    }
    FULLWIDTH_INLINE_BLOCK_REF_REGEX.lastIndex = index;
    const fullwidthMatch = FULLWIDTH_INLINE_BLOCK_REF_REGEX.exec(line);
    if (fullwidthMatch) {
      targets.push({
        from: lineOffset + fullwidthMatch.index,
        to: lineOffset + fullwidthMatch.index + fullwidthMatch[0].length,
        uuid: fullwidthMatch[1],
        mode: "inline"
      });
      index = fullwidthMatch.index + fullwidthMatch[0].length;
      continue;
    }
    index++;
  }
}
function collectRenderTargets(text) {
  var _a;
  const targets = [];
  const lines = text.split("\n");
  let offset = 0;
  let inFrontmatter = ((_a = lines[0]) == null ? void 0 : _a.trim()) === "---";
  let fenceState = null;
  for (let lineIndex = 0; lineIndex < lines.length; lineIndex++) {
    const line = lines[lineIndex];
    if (inFrontmatter) {
      if (lineIndex > 0 && (line.trim() === "---" || line.trim() === "...")) {
        inFrontmatter = false;
      }
      offset += line.length + 1;
      continue;
    }
    if (fenceState) {
      if (isClosingFence(line, fenceState)) {
        fenceState = null;
      }
      offset += line.length + 1;
      continue;
    }
    const nextFenceState = getFenceState(line);
    if (nextFenceState) {
      fenceState = nextFenceState;
      offset += line.length + 1;
      continue;
    }
    scanLineForTargets(line, offset, targets);
    offset += line.length + 1;
  }
  return targets;
}
function createAsyncBlockRendererPlugin(plugin) {
  return import_view3.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.view = view;
        this.runningRenders = /* @__PURE__ */ new Map();
        this.revealedEmbedPos = null;
        this.inlineEmbedWidthCache = /* @__PURE__ */ new Map();
        this.listEmbedLayoutCache = /* @__PURE__ */ new Map();
        this.listEmbedOverlayStates = /* @__PURE__ */ new Map();
        this.listEmbedOverlayEntries = /* @__PURE__ */ new Map();
        this.component = new import_obsidian3.Component();
        plugin.addChild(this.component);
        this.overlayRoot = this.createOverlayRoot();
        this.debouncedScan = this.debounce(this.scanAndRender.bind(this), 200);
        this.debouncedScan();
      }
      update(update) {
        if (this.revealedEmbedPos !== null && update.docChanged) {
          this.revealedEmbedPos = update.changes.mapPos(this.revealedEmbedPos, -1);
        }
        if (update.focusChanged && !this.view.hasFocus) {
          this.revealedEmbedPos = null;
        }
        if (update.docChanged || update.viewportChanged || update.selectionSet || update.focusChanged) {
          this.debouncedScan();
        }
      }
      destroy() {
        this.listEmbedOverlayEntries.forEach((entry) => entry.card.remove());
        this.listEmbedOverlayEntries.clear();
        this.inlineEmbedWidthCache.clear();
        this.listEmbedLayoutCache.clear();
        this.overlayRoot.remove();
        this.view.scrollDOM.classList.remove("logseq-overlay-host");
        this.component.unload();
        this.runningRenders.forEach(({ controller }) => controller.abort());
      }
      createOverlayRoot() {
        this.view.scrollDOM.classList.add("logseq-overlay-host");
        const root = document.createElement("div");
        root.className = "logseq-live-preview-overlay-root";
        this.view.scrollDOM.appendChild(root);
        return root;
      }
      debounce(func, delay) {
        let timeout;
        return () => {
          clearTimeout(timeout);
          timeout = setTimeout(func, delay);
        };
      }
      selectionOverlapsRange(from, to) {
        return this.view.state.selection.ranges.some((range) => range.from <= to && range.to >= from);
      }
      measureListEmbedLayout(target) {
        var _a, _b;
        const lineStartCoords = this.view.coordsAtPos(target.from);
        const markerCoords = target.listMarkerPos !== void 0 ? this.view.coordsAtPos(target.listMarkerPos) : null;
        const contentPos = (_b = (_a = target.listContentPos) != null ? _a : target.revealPos) != null ? _b : target.from;
        const contentCoords = this.view.coordsAtPos(contentPos);
        const lineBlock = this.view.lineBlockAt(target.from);
        if (!lineStartCoords || !markerCoords || !contentCoords) {
          return null;
        }
        const markerOffsetPx = Math.max(Math.round(markerCoords.left - lineStartCoords.left), 0);
        const contentOffsetPx = Math.max(Math.round(contentCoords.left - lineStartCoords.left), 0);
        if (contentOffsetPx <= markerOffsetPx + 4) {
          return null;
        }
        return {
          markerOffsetPx,
          contentOffsetPx,
          lineHeight: Math.max(Math.round(lineBlock.height), 0)
        };
      }
      measureInlineEmbedWidth(target) {
        const anchorCoords = this.view.coordsAtPos(target.from);
        const contentRect = this.view.contentDOM.getBoundingClientRect();
        if (!anchorCoords || contentRect.width <= 0) {
          return null;
        }
        const availableWidthPx = Math.max(
          Math.round(contentRect.right - anchorCoords.left - 8),
          0
        );
        if (availableWidthPx <= 0) {
          return null;
        }
        return { availableWidthPx };
      }
      measureRenderTarget(target) {
        var _a, _b, _c, _d;
        if (target.preserveListMarker) {
          const refId2 = getTargetRefId(target);
          const measuredWidth = this.measureInlineEmbedWidth(target);
          if (measuredWidth) {
            this.inlineEmbedWidthCache.set(refId2, measuredWidth);
          }
          const inlineWidth = measuredWidth != null ? measuredWidth : this.inlineEmbedWidthCache.get(refId2);
          if (!inlineWidth) {
            return target;
          }
          return {
            ...target,
            availableInlineWidthPx: inlineWidth.availableWidthPx
          };
        }
        if (!target.renderAsListItem) {
          return target;
        }
        const refId = getTargetRefId(target);
        const measuredLayout = this.measureListEmbedLayout(target);
        if (measuredLayout) {
          this.listEmbedLayoutCache.set(refId, measuredLayout);
        }
        const layout = measuredLayout != null ? measuredLayout : this.listEmbedLayoutCache.get(refId);
        if (!layout) {
          return {
            ...target,
            reservedHeightPx: (_b = (_a = this.listEmbedOverlayStates.get(refId)) == null ? void 0 : _a.reservedHeightPx) != null ? _b : 0
          };
        }
        return {
          ...target,
          listMarkerOffsetPx: layout.markerOffsetPx,
          listContentOffsetPx: layout.contentOffsetPx,
          lineHeightPx: layout.lineHeight,
          reservedHeightPx: (_d = (_c = this.listEmbedOverlayStates.get(refId)) == null ? void 0 : _c.reservedHeightPx) != null ? _d : 0
        };
      }
      buildListEmbedCard(target, html) {
        var _a;
        const card = document.createElement("div");
        card.className = "logseq-block-ref-enhancer-widget logseq-block-embed-widget markdown-rendered is-list-embed-card logseq-live-preview-overlay-card";
        card.dataset.logseqFrom = String(target.from);
        card.dataset.logseqTo = String(target.to);
        card.dataset.logseqRevealPos = String((_a = target.revealPos) != null ? _a : target.from);
        card.dataset.logseqRefId = getTargetRefId(target);
        card.innerHTML = `<div class="logseq-live-preview-embed-layout is-list-card"><div class="logseq-block-embed logseq-live-preview-embed-card">${html}</div></div>`;
        this.overlayRoot.appendChild(card);
        return card;
      }
      updateListEmbedCardPosition(card, target) {
        var _a, _b, _c, _d;
        card.style.left = `${(_a = target.anchorLeftPx) != null ? _a : 0}px`;
        card.style.top = `${(_b = target.anchorTopPx) != null ? _b : 0}px`;
        card.style.width = `${(_c = target.anchorWidthPx) != null ? _c : 0}px`;
        card.style.maxWidth = `${(_d = target.anchorWidthPx) != null ? _d : 0}px`;
      }
      syncListEmbedOverlay(target) {
        const refId = getTargetRefId(target);
        const state = this.listEmbedOverlayStates.get(refId);
        if (!state) {
          const existing2 = this.listEmbedOverlayEntries.get(refId);
          if (existing2) {
            existing2.card.remove();
            this.listEmbedOverlayEntries.delete(refId);
          }
          return;
        }
        const existing = this.listEmbedOverlayEntries.get(refId);
        if (!existing) {
          const card = this.buildListEmbedCard(target, state.html);
          this.updateListEmbedCardPosition(card, target);
          this.listEmbedOverlayEntries.set(refId, { card, state });
          return;
        }
        if (existing.state.html !== state.html) {
          existing.card.innerHTML = `<div class="logseq-live-preview-embed-layout is-list-card"><div class="logseq-block-embed logseq-live-preview-embed-card">${state.html}</div></div>`;
          existing.state = state;
        }
        this.updateListEmbedCardPosition(existing.card, target);
      }
      syncListEmbedOverlays(targets) {
        const activeRefIds = /* @__PURE__ */ new Set();
        for (const target of targets) {
          if (!target.renderAsListItem) {
            continue;
          }
          const refId = getTargetRefId(target);
          activeRefIds.add(refId);
          this.syncListEmbedOverlay(target);
        }
        for (const [refId, entry] of this.listEmbedOverlayEntries.entries()) {
          if (activeRefIds.has(refId)) {
            continue;
          }
          entry.card.remove();
          this.listEmbedOverlayEntries.delete(refId);
        }
      }
      syncRevealedEmbedTarget(targets) {
        var _a, _b, _c;
        if (this.revealedEmbedPos === null) {
          return;
        }
        const activeTarget = targets.find((target) => {
          var _a2, _b2;
          if (target.mode !== "embed") {
            return false;
          }
          const revealFrom2 = (_a2 = target.revealFrom) != null ? _a2 : target.from;
          const revealTo2 = (_b2 = target.revealTo) != null ? _b2 : target.to;
          return this.revealedEmbedPos !== null && this.revealedEmbedPos >= revealFrom2 && this.revealedEmbedPos <= revealTo2;
        });
        if (!activeTarget) {
          this.revealedEmbedPos = null;
          return;
        }
        const revealFrom = (_a = activeTarget.revealFrom) != null ? _a : activeTarget.from;
        const revealTo = (_b = activeTarget.revealTo) != null ? _b : activeTarget.to;
        if (!this.selectionOverlapsRange(revealFrom, revealTo)) {
          this.revealedEmbedPos = null;
          return;
        }
        this.revealedEmbedPos = (_c = activeTarget.revealPos) != null ? _c : activeTarget.from;
      }
      shouldRevealSource(target) {
        var _a, _b, _c, _d;
        if (target.mode === "inline") {
          const revealFrom2 = (_a = target.revealFrom) != null ? _a : target.from;
          const revealTo2 = (_b = target.revealTo) != null ? _b : target.to;
          return this.selectionOverlapsRange(revealFrom2, revealTo2);
        }
        if (this.revealedEmbedPos === null) {
          return false;
        }
        const revealFrom = (_c = target.revealFrom) != null ? _c : target.from;
        const revealTo = (_d = target.revealTo) != null ? _d : target.to;
        return this.revealedEmbedPos >= revealFrom && this.revealedEmbedPos <= revealTo;
      }
      revealEmbedSource(from, to, revealPos, refId) {
        const runningTask = this.runningRenders.get(from);
        if (runningTask) {
          runningTask.controller.abort();
          this.runningRenders.delete(from);
        }
        this.revealedEmbedPos = revealPos;
        this.view.focus();
        this.view.dispatch({
          selection: import_state2.EditorSelection.single(revealPos),
          effects: removeWidgetEffect.of({ from, to, refId }),
          scrollIntoView: true
        });
      }
      handleEmbedRevealPointer(event) {
        if (event.button !== 0) {
          return false;
        }
        const target = event.target;
        if (!(target instanceof HTMLElement)) {
          return false;
        }
        const widget = target.closest(".logseq-block-embed-widget");
        if (!(widget instanceof HTMLElement)) {
          return false;
        }
        const from = Number(widget.dataset.logseqFrom);
        const to = Number(widget.dataset.logseqTo);
        const revealPos = Number(widget.dataset.logseqRevealPos);
        const refId = widget.dataset.logseqRefId;
        if (!Number.isFinite(from) || !Number.isFinite(to) || !Number.isFinite(revealPos)) {
          return false;
        }
        event.preventDefault();
        event.stopPropagation();
        this.revealEmbedSource(from, to, revealPos, refId);
        return true;
      }
      scanAndRender() {
        const currentWidgets = this.view.state.field(blockReferenceField);
        const doc = this.view.state.doc;
        const rawTargets = collectRenderTargets(doc.sliceString(0, doc.length));
        this.syncRevealedEmbedTarget(rawTargets);
        const targets = rawTargets.map((target) => this.measureRenderTarget(target));
        const activeTargets = /* @__PURE__ */ new Map();
        const activeTargetsByRefId = /* @__PURE__ */ new Map();
        for (const target of targets) {
          if (!this.shouldRevealSource(target)) {
            activeTargets.set(target.from, target);
            activeTargetsByRefId.set(getTargetRefId(target), target);
          }
        }
        for (const [from, task] of this.runningRenders.entries()) {
          const target = activeTargets.get(from);
          if (!target || task.signature !== buildRenderSignature(target)) {
            task.controller.abort();
            this.runningRenders.delete(from);
          }
        }
        const existingDecorations = /* @__PURE__ */ new Set();
        const removeEffects = [];
        const queuedRemovals = /* @__PURE__ */ new Set();
        currentWidgets.between(0, doc.length, (from, to, decoration) => {
          const refId = decoration.spec.logseqRefId;
          const signature = decoration.spec.logseqSignature;
          const target = refId ? activeTargetsByRefId.get(refId) : activeTargets.get(from);
          const shouldKeep = target !== void 0 && signature === buildTargetSignature(target) && (refId !== void 0 || target.to === to);
          if (shouldKeep) {
            existingDecorations.add(target.from);
            return;
          }
          const removalKey = refId != null ? refId : `${from}:${to}`;
          if (queuedRemovals.has(removalKey)) {
            return;
          }
          queuedRemovals.add(removalKey);
          removeEffects.push(removeWidgetEffect.of({ from, to, refId }));
        });
        if (removeEffects.length > 0) {
          this.view.dispatch({ effects: removeEffects });
        }
        for (const target of activeTargets.values()) {
          if (!existingDecorations.has(target.from) && !this.runningRenders.has(target.from)) {
            this.triggerRender(target);
          }
        }
      }
      async triggerRender(target) {
        var _a, _b, _c, _d, _e;
        const controller = new AbortController();
        const renderSignature = buildRenderSignature(target);
        const widgetSignature = buildTargetSignature(target);
        this.runningRenders.set(target.from, { controller, signature: renderSignature });
        try {
          this.view.dispatch({
            effects: addLoadingWidgetEffect.of({
              from: target.from,
              to: target.to,
              uuid: target.uuid,
              mode: target.mode,
              interaction: target.mode === "embed" ? {
                from: target.from,
                to: target.to,
                revealPos: (_a = target.revealPos) != null ? _a : target.from,
                blockWidget: target.blockWidget,
                preserveListMarker: target.preserveListMarker,
                availableInlineWidthPx: target.availableInlineWidthPx,
                listPrefixColumns: target.renderAsListItem ? target.indentColumns : void 0,
                listMarkerOffsetPx: target.listMarkerOffsetPx,
                listContentOffsetPx: target.listContentOffsetPx,
                cardPos: target.cardPos,
                refId: getTargetRefId(target),
                signature: widgetSignature,
                lineHeightPx: target.lineHeightPx,
                reservedHeightPx: target.reservedHeightPx
              } : void 0
            })
          });
          if (target.mode === "inline") {
            const summary = (_b = plugin.getInlineReferenceText(target.uuid)) != null ? _b : "[missing block]";
            if (controller.signal.aborted) {
              return;
            }
            this.view.dispatch({
              effects: setRenderedWidgetEffect.of({
                from: target.from,
                to: target.to,
                content: summary,
                mode: "inline"
              })
            });
            return;
          }
          const sourcePath = (_d = (_c = this.view.state.field(import_obsidian3.editorInfoField).file) == null ? void 0 : _c.path) != null ? _d : "";
          const embedInnerHtml = await plugin.buildEmbedHtml(target.uuid, sourcePath, this.component);
          const html = `<div class="logseq-live-preview-embed-layout"><div class="logseq-block-embed logseq-live-preview-embed-card">${embedInnerHtml}</div></div>`;
          if (controller.signal.aborted) {
            return;
          }
          this.view.dispatch({
            effects: setRenderedWidgetEffect.of({
              from: target.from,
              to: target.to,
              content: html,
              mode: "embed",
              interaction: {
                from: target.from,
                to: target.to,
                revealPos: (_e = target.revealPos) != null ? _e : target.from,
                blockWidget: target.blockWidget,
                preserveListMarker: target.preserveListMarker,
                availableInlineWidthPx: target.availableInlineWidthPx,
                listPrefixColumns: target.renderAsListItem ? target.indentColumns : void 0,
                listMarkerOffsetPx: target.listMarkerOffsetPx,
                listContentOffsetPx: target.listContentOffsetPx,
                cardPos: target.cardPos,
                refId: getTargetRefId(target),
                signature: widgetSignature,
                lineHeightPx: target.lineHeightPx,
                reservedHeightPx: target.reservedHeightPx
              }
            })
          });
        } catch (error) {
          console.error("Logseq Block Ref Enhancer Error:", error);
        } finally {
          const runningTask = this.runningRenders.get(target.from);
          if ((runningTask == null ? void 0 : runningTask.signature) === renderSignature) {
            this.runningRenders.delete(target.from);
          }
        }
      }
    },
    {
      eventHandlers: {
        mousedown(event) {
          return this.handleEmbedRevealPointer(event);
        }
      }
    }
  );
}

// src/main.ts
var DEFAULT_SETTINGS = {
  // 默认值
};
var MAX_INLINE_SUMMARY_LENGTH = 60;
var STANDALONE_EMBED_REGEX = /^\s*\{\{embed\s+\(\(([A-Za-z0-9_-]{36,})\)\)\s*\}\}\s*$/;
var MANUAL_RENDER_SCOPE_ATTR = "data-logseq-manual-render";
var MANAGED_NODE_ATTR = "data-logseq-managed-node";
function createBlockReferenceRegex() {
  return /\{\{embed\s+\(\(([A-Za-z0-9_-]{36,})\)\)\s*\}\}|\(\(([A-Za-z0-9_-]{36,})\)\)|（（([A-Za-z0-9_-]{36,})））/g;
}
var ReferencePostProcessChild = class extends import_obsidian4.MarkdownRenderChild {
  constructor(containerEl, plugin, sourcePath) {
    super(containerEl);
    this.plugin = plugin;
    this.sourcePath = sourcePath;
  }
  async onload() {
    await this.plugin.processRenderedReferences(this.containerEl, this.sourcePath, this, /* @__PURE__ */ new Set());
  }
};
var LogseqBlockRefEnhancer = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.indexService = new IndexService(this.app, this.manifest.dir);
    this.addCommand({
      id: "rebuild-logseq-block-index",
      name: "Rebuild block reference index",
      callback: () => {
        this.indexService.buildIndex();
      }
    });
    this.addCommand({
      id: "copy-logseq-block-reference",
      name: "Copy current block's Logseq reference",
      editorCallback: (editor, view) => {
        this.handleCopyBlockReference(editor, view);
      }
    });
    this.app.workspace.onLayoutReady(async () => {
      await this.indexService.initialize();
      this.registerMarkdownPostProcessor(this.readingModeRenderer.bind(this));
      const asyncPlugin = createAsyncBlockRendererPlugin(this);
      this.registerEditorExtension([blockReferenceField, asyncPlugin]);
      this.registerEditorSuggest(new BlockSuggest(this.app, this.indexService));
      this.setupFileEvents();
    });
  }
  setupFileEvents() {
    this.registerEvent(this.app.vault.on("create", (file) => {
      if (file instanceof import_obsidian4.TFile && file.extension === "md") {
        this.indexService.processFileChange(file);
      }
    }));
    this.registerEvent(this.app.vault.on("modify", (file) => {
      if (file instanceof import_obsidian4.TFile && file.extension === "md") {
        this.indexService.processFileChange(file);
      }
    }));
    this.registerEvent(this.app.vault.on("delete", (file) => {
      if (file instanceof import_obsidian4.TFile && file.extension === "md") {
        this.indexService.processFileDelete(file.path);
      }
    }));
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
      if (file instanceof import_obsidian4.TFile && file.extension === "md") {
        this.indexService.processFileRename(oldPath, file.path);
      }
    }));
  }
  onunload() {
    console.log("Unloading Logseq Block Ref Enhancer plugin.");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async handleCopyBlockReference(editor, view) {
    const file = view.file;
    if (!file)
      return;
    const cursor = editor.getCursor();
    const line = cursor.line;
    const lineContent = editor.getLine(line);
    const blockMatch = lineContent.match(/^\s*-\s(.+)/);
    if (!blockMatch) {
      new import_obsidian4.Notice("This line is not a valid Logseq block.");
      return;
    }
    let existingBlock = this.indexService.findBlockByFileAndLine(file.path, line);
    let blockId;
    if (existingBlock) {
      blockId = existingBlock.id;
    } else {
      blockId = crypto.randomUUID();
      const indentationMatch = lineContent.match(/^(\s*)/);
      const indentation = indentationMatch ? indentationMatch[1] : "";
      const idLine = `
${indentation}  id:: ${blockId}`;
      editor.replaceRange(idLine, { line, ch: lineContent.length });
      this.indexService.addBlock(blockId, {
        filePath: file.path,
        rawContent: blockMatch[1],
        childrenMarkdown: "",
        startLine: line,
        childrenIDs: []
      });
    }
    navigator.clipboard.writeText(`((${blockId}))`);
    new import_obsidian4.Notice("Block reference copied to clipboard!");
  }
  getInlineReferenceText(uuid) {
    return this.getInlineReferenceTextInternal(uuid, /* @__PURE__ */ new Set());
  }
  getInlineReferenceTextInternal(uuid, visited) {
    var _a;
    if (visited.has(uuid)) {
      return "[cyclic block]";
    }
    const block = this.indexService.getBlock(uuid);
    if (!block) {
      return null;
    }
    const nextVisited = new Set(visited);
    nextVisited.add(uuid);
    const firstLine = (_a = block.rawContent.split(/\r?\n/, 1)[0]) != null ? _a : "";
    const expandedLine = firstLine.replace(/(?:\(\(|\uFF08\uFF08)([A-Za-z0-9_-]{36,})(?:\)\)|\uFF09\uFF09)/g, (_match, nestedUuid) => {
      var _a2;
      return (_a2 = this.getInlineReferenceTextInternal(nestedUuid, nextVisited)) != null ? _a2 : "[missing block]";
    });
    const plainText = expandedLine.replace(/!\[\[([^\]]+)\]\]/g, "$1").replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, "$2").replace(/\[\[([^\]]+)\]\]/g, "$1").replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").replace(/^#{1,6}\s+/g, "").replace(/[*_~`]/g, "").replace(/\s+/g, " ").trim();
    const summary = plainText || "[empty block]";
    return summary.length > MAX_INLINE_SUMMARY_LENGTH ? `${summary.slice(0, MAX_INLINE_SUMMARY_LENGTH).trimEnd()}\u2026` : summary;
  }
  async buildEmbedHtml(uuid, sourcePath, component) {
    const host = document.createElement("div");
    await this.populateEmbedContainer(host, uuid, sourcePath, component, /* @__PURE__ */ new Set());
    return host.innerHTML;
  }
  markManualRenderScope(element) {
    element.setAttribute(MANUAL_RENDER_SCOPE_ATTR, "true");
  }
  createInlineReferenceElement(summary) {
    const inlineRef = document.createElement("span");
    inlineRef.addClass("logseq-inline-block-ref");
    inlineRef.setAttribute(MANAGED_NODE_ATTR, "true");
    inlineRef.setText(summary);
    return inlineRef;
  }
  shouldSkipTextNode(node, root) {
    const parentElement = node.parentElement;
    if (!parentElement || !root.contains(parentElement)) {
      return true;
    }
    if (parentElement.closest("code, pre, .metadata-container, .frontmatter, .mod-frontmatter")) {
      return true;
    }
    const managedAncestor = parentElement.closest(`[${MANAGED_NODE_ATTR}="true"]`);
    return managedAncestor !== null;
  }
  async renderMarkdownAndProcess(container, markdown, sourcePath, component, visitedEmbeds) {
    if (!markdown.trim()) {
      return;
    }
    this.markManualRenderScope(container);
    await import_obsidian4.MarkdownRenderer.render(this.app, markdown, container, sourcePath, component);
    await this.processRenderedReferences(container, sourcePath, component, visitedEmbeds);
  }
  async populateEmbedContainer(container, uuid, sourcePath, component, visitedEmbeds) {
    var _a;
    container.empty();
    container.addClass("logseq-block-embed");
    this.markManualRenderScope(container);
    if (visitedEmbeds.has(uuid)) {
      container.addClass("logseq-block-ref-enhancer-error");
      container.setText("Cyclic embed");
      return;
    }
    const block = this.indexService.getBlock(uuid);
    if (!block) {
      container.addClass("logseq-block-ref-enhancer-error");
      container.setText("Missing block");
      return;
    }
    const nextVisitedEmbeds = new Set(visitedEmbeds);
    nextVisitedEmbeds.add(uuid);
    const rootContainer = document.createElement("div");
    rootContainer.addClass("logseq-block-embed-root");
    container.appendChild(rootContainer);
    await this.renderMarkdownAndProcess(rootContainer, block.rawContent, sourcePath, component, nextVisitedEmbeds);
    const childMarkdown = (_a = block.childrenMarkdown) == null ? void 0 : _a.trim();
    if (childMarkdown) {
      const childrenContainer = document.createElement("div");
      childrenContainer.addClass("logseq-block-embed-children");
      container.appendChild(childrenContainer);
      await this.renderMarkdownAndProcess(childrenContainer, childMarkdown, sourcePath, component, nextVisitedEmbeds);
    }
  }
  async processRenderedReferences(element, sourcePath, component, visitedEmbeds) {
    var _a, _b, _c, _d;
    const probeRegex = createBlockReferenceRegex();
    const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
    const nodesToProcess = [];
    while (walker.nextNode()) {
      const node = walker.currentNode;
      if (this.shouldSkipTextNode(node, element)) {
        continue;
      }
      if (node.nodeValue && probeRegex.test(node.nodeValue)) {
        nodesToProcess.push(node);
      }
      probeRegex.lastIndex = 0;
    }
    for (const node of nodesToProcess) {
      if (!node.nodeValue || !node.parentNode) {
        continue;
      }
      const text = node.nodeValue;
      const standaloneEmbedMatch = text.match(STANDALONE_EMBED_REGEX);
      if (standaloneEmbedMatch) {
        const embedHost = document.createElement("div");
        const parentElement = node.parentElement;
        if ((parentElement == null ? void 0 : parentElement.tagName) === "P") {
          parentElement.replaceWith(embedHost);
        } else {
          (_a = node.parentNode) == null ? void 0 : _a.replaceChild(embedHost, node);
        }
        await this.populateEmbedContainer(embedHost, standaloneEmbedMatch[1], sourcePath, component, visitedEmbeds);
        continue;
      }
      let lastIndex = 0;
      let match;
      let replacedInline = false;
      const fragment = document.createDocumentFragment();
      const replaceRegex = createBlockReferenceRegex();
      while (match = replaceRegex.exec(text)) {
        const embedUuid = match[1];
        const inlineUuid = (_b = match[2]) != null ? _b : match[3];
        const placeholder = match[0];
        const start = match.index;
        fragment.appendChild(document.createTextNode(text.slice(lastIndex, start)));
        if (embedUuid) {
          fragment.appendChild(document.createTextNode(placeholder));
        } else {
          const summary = (_c = this.getInlineReferenceText(inlineUuid)) != null ? _c : "[missing block]";
          fragment.appendChild(this.createInlineReferenceElement(summary));
          replacedInline = true;
        }
        lastIndex = start + placeholder.length;
      }
      if (!replacedInline) {
        continue;
      }
      fragment.appendChild(document.createTextNode(text.slice(lastIndex)));
      (_d = node.parentNode) == null ? void 0 : _d.replaceChild(fragment, node);
    }
  }
  async readingModeRenderer(element, context) {
    if (element.closest(`[${MANUAL_RENDER_SCOPE_ATTR}="true"]`)) {
      return;
    }
    context.addChild(new ReferencePostProcessChild(element, this, context.sourcePath));
  }
};
